### ISSUE TITLE
Inquiry Regarding the Version of G-PCC Used for Comparison in Your Paper

### ISSUE THREAD

**Issue by kai0416s** [mic-rud/ProgressivePCAC#2]
Thank you for your excellent open-source work. 
After reading your published paper, I noticed that it seems there is no mention of which version of G-PCC you compared with (Octree-RAHT or another mode)? 

I look forward to your reply. Thank you!

**Comment by mic-rud** [comment]
Dear @kai0416s,

thanks for your interest in our work. We used G-PCC (v14) with predlift (lossless geometry mode). 
For the computation of the bpp, we omitted the geometry bitstream parts and only looked at the bits required for attribute compression. 

Best regards,
Michael
